### ISSUE TITLE
Sync view when a scene is selected

### ISSUE THREAD

**Issue by JorgeRaphael** [SeamusFinlayson/phases-automated#3]
I like to use this extension to create various environments where characters are acting, especially when the team splits up. Then I activate the scene that is taking place in the current narrative. Is there any way to synchronize the previously adjusted view for all participants when activating the scene?

**Comment by SeamusFinlayson** [comment]
That's kinda beyond the scope of this project, I think your looking for this extension: https://extensions.owlbear.rodeo/default-view
